# Generated by Django 3.0.6 on 2020-05-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pGender', models.TextField()),
                ('pFname', models.CharField(max_length=150)),
                ('pLname', models.CharField(max_length=150)),
                ('pDOB', models.DateField()),
                ('pheight', models.IntegerField()),
                ('pweight', models.IntegerField()),
                ('pemail', models.CharField(max_length=300)),
            ],
        ),
    ]
