# Generated by Django 3.0.6 on 2020-05-20 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generaldetails',
            old_name='pemail',
            new_name='pEmail',
        ),
        migrations.RenameField(
            model_name='generaldetails',
            old_name='pheight',
            new_name='pHeight',
        ),
        migrations.RenameField(
            model_name='generaldetails',
            old_name='pweight',
            new_name='pWeight',
        ),
    ]
