# Generated by Django 3.0.6 on 2020-05-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20200520_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugList', models.TextField()),
                ('disList', models.TextField()),
                ('curMed', models.TextField()),
                ('comments', models.TextField()),
            ],
        ),
    ]
