# Generated by Django 3.0.6 on 2020-05-20 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_medicalhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='drugList',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mymodel', to='hospital.GeneralDetails'),
        ),
    ]
