# Generated by Django 3.0.6 on 2020-05-20 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_auto_20200520_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalhistory',
            name='pname',
        ),
    ]
