# Generated by Django 3.0.6 on 2020-05-20 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_remove_medicalhistory_pname'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaldetails',
            name='pID',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='patient_Id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='medical', to='hospital.GeneralDetails'),
        ),
    ]
