# Generated by Django 3.0.6 on 2020-05-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_remove_generaldetails_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaldetails',
            name='pId',
            field=models.IntegerField(default=None),
        ),
    ]
