# Generated by Django 3.0.6 on 2020-05-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_auto_20200522_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='comments',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='curMed',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='drugList',
            field=models.TextField(default=None),
        ),
    ]
