# Generated by Django 3.0.6 on 2020-05-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_auto_20200522_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='comments',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='curMed',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='drugList',
            field=models.TextField(default='NA'),
        ),
    ]
